### ISSUE TITLE
Add a README.md

### ISSUE THREAD

**Issue by frinyvonnick** [Zenika/immutadot#1]
- [x] Description and philosophy (fix in #38)
- [x] Usage
- [x] Documentation
- [x] Contributing
- ~Troubleshooting~
- ~Credits~

**Comment by nlepage** [comment]
Additionally I'd like to have a github.io page looking like lodash documentation

**Comment by nlepage** [comment]
see #12 for the documentation

**Comment by nlepage** [comment]
It would be nice to highlight that :
- immutadot is mainly designed as a helper lib for redux
- immutadot is largely based on lodash and lodash/fp

Also add simple examples with an es6 version and an immutadot version of the code

**Comment by nlepage** [comment]
In addition of the README, add a code of conduct and contributor guidelines.
See https://github.com/Zenika/immutadot/community
