### ISSUE TITLE
:bug: Chaining with nested array fails

### ISSUE THREAD

**Issue by mbernardeau** [Zenika/immutadot#117]
### Prerequisites
 - [x] I have read the [Contributing guidelines](https://github.com/Zenika/immutadot/blob/master/.github/CONTRIBUTING.md)
 - [x] I have read the [Code of conduct](https://github.com/Zenika/immutadot/blob/master/.github/CODE_OF_CONDUCT.md) and I agree with it

### Description
Given the following initial state:

```javascript
const initialState = {
    histories: {
        persons: [{
            id: '1'
        }]
    }
}
```

I want to perform a series of actions on the nested `persons` array (see below).

The following doesn't work as expected:

```javascript
const action = {
   person: {
       id: '2'
   }
}

immutadot.chain(state, 'histories.persons')
        .reject((p) => p.id === action.person.id) // remove from array if person already exists
        .unshift(action.person) // add person at start of the array
        .slice(0, 10) // Limit size of history to 10 elements
        .value()

=> 
// {
//    histories: {
//        persons: [
//           []
//        ]
//    }
//}
```

Note that using the chaining with the path at each operation, it works as expected:
```javascript
immutadot.chain(state)
        .reject('histories.persons', (p) => p.id === action.person.id)
        .unshift('histories.persons', action.person)
        .slice('histories.persons', 0, 10)
        .value()
=> 
// {
//    histories: {
//        persons: [{
//           id: '2'
//        }, {
//           id: '1'
//       ]
//    }
//}
```
### Only for bugs :bug:
**Version :** 0.3.2

#### Expected behavior
Both snippets should give the same result

#### Actual behavior
Chaining on a path gives unexpected results

#### How to reproduce
https://runkit.com/mbernardeau/runkit-npm-immutadot

**Comment by nlepage** [comment]
The intent of the second param of `chain` is to allow making subsequent calls on **subpaths**.
See this example (`set` and `unset` are called on different subpaths) :
```js
chain({ nested: { prop1: 'old', prop2: 1 } }, 'nested')
  .set('prop1', 'new')
  .unset('prop2')
  .value() // => { nested: { prop1: 'new' } }
```

In your case I would rather do this :
```js
immutadot.update(state, 'histories.persons', persons => {
  // here use lodash chain
  return chain(persons)
    .reject(p) => p.id === action.person.id)
    .unshift(action.person)
    .slice(0, 10)
    .value()
})
```

Is this ok with you ?

**Comment by mbernardeau** [comment]
Nice using update gives the expected result, I guess I just misinterpreted the use of the chaining method.

Thank you
