### ISSUE TITLE
Add a getting started in documentation

### ISSUE THREAD

**Issue by frinyvonnick** [Zenika/immutadot#174]
### Prerequisites
 - [x] I have read the [Contributing guidelines](https://github.com/Zenika/immutadot/blob/master/.github/CONTRIBUTING.md)
 - [x] I have read the [Code of conduct](https://github.com/Zenika/immutadot/blob/master/.github/CODE_OF_CONDUCT.md) and I agree with it

### Description
Add a getting started in documentation to make easier for newcomers to start with immutadot.

It will focus on introducing immutadot main features like:

- Setting nested properties
- Basic array operations
- Basic collection operations
- Grouping multiple operations
- Performing custom updates (`core.update`)
- Creating custom operations (`core.convert`)
- A section about path notation that link #132

**Comment by nlepage** [comment]
Add a section about "Grouping multiple operations" showing `chain` and `flow`, before the section about path notation ?

**Comment by nlepage** [comment]
Two more sections I think we could add :
 - Performing custom updates (`core.update`)
 - Creating custom operations (`core.convert`)

**Comment by nlepage** [comment]
closed by #182
