### ISSUE TITLE
Update documentation to reflect the new organization

### ISSUE THREAD

**Issue by nlepage** [Zenika/immutadot#183]

**Comment by sriikanth** [comment]
@nlepage Is the issue still open? 
Can I take it?

**Comment by nlepage** [comment]
Hi @sriikanth ! @frinyvonnick is currently working on this in #172, his work needs reviewing and he might need help, you should ask him. Thank you for your interest. :+1:

**Comment by frinyvonnick** [comment]
Hi @sriikanth, here is my progression on this issue: 

- [x] CONTRIBUTING.md 
- [ ] README.md
  - [x] Top level examples 
  - [x] Introducing examples for newcomers 
  - [ ] Path notation
      - [x] Slice notation
      - [ ] List notation
      - [x] Performances

I have difficulties to find a good example to show how list notation works. I based my other examples on the following structure:


```js
const animals = {
  weasels: [
    {
      vernacularName: 'badger',
      scientificName: 'Meles meles'
    },
    {
      vernacularName: 'otter',
    }
  ]
}
```

Do you have an idea ?

**Comment by frinyvonnick** [comment]
The checked items in my previous message were done in #172

**Comment by frinyvonnick** [comment]
This has been finished in #182
