### ISSUE TITLE
Greenkeeper: No lock file update

### ISSUE THREAD

**Issue by nlepage** [Zenika/immutadot#184]
Since Circle CI 2, it seems that yarn.lock isn't updated anymore in greenkeeper's PRs.

**Comment by charlyx** [comment]
https://github.com/greenkeeperio/greenkeeper-lockfile#circleci-workflows

**Comment by fabienjuif** [comment]
I try that but it seems not to work for me...
 - CircleCI config: https://github.com/alakarteio/k-ramel/blob/master/.circleci/config.yml
 - One of the last PR I had to manually update yarn.lock: https://github.com/alakarteio/k-ramel/pull/96
 - Detail of the `lockfile` job for this last PR: https://circleci.com/gh/alakarteio/k-ramel/396?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
   - `Only running on first push of a new branch`

So I am interested if you know how to fix that :)

**Comment by frinyvonnick** [comment]
I updated .circleci accordingly to the documentation but it seems that we'll have to wait until greenkeeper next PR because lockfile update works only on first script run...

![image](https://user-images.githubusercontent.com/13099512/36351353-e720d134-14a8-11e8-8e67-6f0139e4824a.png)

**Comment by frinyvonnick** [comment]
@fabienjuif Greenkeeper seems to have issues supporting monorepo like ones made with lerna https://github.com/greenkeeperio/greenkeeper/issues/594

**Comment by fabienjuif** [comment]
@frinyvonnick you have same issue than me : 
https://github.com/Zenika/immutadot/commits/greenkeeper/lerna-3.0.0-alpha.1

> You can see that there is no yarn.lock updated

The screenshot you linked to me is what I send you in my first comment ;)
