### ISSUE TITLE
Add an explicit error when a function is missing on ChainWrapper

### ISSUE THREAD

**Issue by frinyvonnick** [Zenika/immutadot#193]
### Prerequisites
 - [x] I have read the [Contributing guidelines](https://github.com/Zenika/immutadot/blob/master/.github/CONTRIBUTING.md)
 - [x] I have read the [Code of conduct](https://github.com/Zenika/immutadot/blob/master/.github/CODE_OF_CONDUCT.md) and I agree with it

### Description
Add an explicit error when a function is missing on ChainWrapper

example: 
```
"set" function is missing on ChainWrapper. Did you forget to import it ?
```

**Comment by nlepage** [comment]
If we merge #197 this will be invalid

**Comment by nlepage** [comment]
This is now irrelevant
