### ISSUE TITLE
Remove util.using

### ISSUE THREAD

**Issue by nlepage** [Zenika/immutadot#200]
Remove `using` of util namespace, it imports all of immutadot (like `chain`) and thus doesn't allow for tree shaking.

It can already be replaced by :
```js
// Instead of using('nested.a').set(input, path)
set(obj, 'nested.b', get(obj, 'nested.a'))
```
Unlike `using` get allows a default value.

And maybe we could allow something like this :
```js
// Instead of using('nested.a').set(input, path)
set(obj, 'nested.b', get('nested.a'))
```

**Comment by frinyvonnick** [comment]
I agree about removing using. I'm fine with the current way to replace it maybe we should wait for more feedback before doing anything.

**Comment by nlepage** [comment]
:+1: let's remove `using` and publish 1.0.0-rc.5
I'll create a new issue for a currified `get`
