### ISSUE TITLE
Missing PATH_NOTATION documentation

### ISSUE THREAD

**Issue by Errorname** [Zenika/immutadot#243]
### Prerequisites
 - [x] I have read the [Contributing guidelines](https://github.com/Zenika/immutadot/blob/master/.github/CONTRIBUTING.md)
 - [x] I have read the [Code of conduct](https://github.com/Zenika/immutadot/blob/master/.github/CODE_OF_CONDUCT.md) and I agree with it

### Description
Both `docs/GETTING_STARTED.md` and `docs/MIGRATING_TO_1_0.md` are referencing a missing `docs/PATH_NOTATION.md`

**Comment by frinyvonnick** [comment]
Sure it's actually a work in progress https://github.com/Zenika/immutadot/pull/222
