### ISSUE TITLE
Apply modifications on object root

### ISSUE THREAD

**Issue by thcolin** [Zenika/immutadot#274]
### Prerequisites
 - [x] I have read the [Contributing guidelines](https://github.com/Zenika/immutadot/blob/master/.github/CONTRIBUTING.md)
- [x] I have read the [Code of conduct](https://github.com/Zenika/immutadot/blob/master/.github/CODE_OF_CONDUCT.md) and I agree with it
### Description
I can't assign values on object root like I sometimes do in vanilla:

```js
Object.assign({}, { entities: {}, result: [] })
```

### Only for bugs :bug:
**Version :** 1.0.0

#### Expected behavior
Be able to assign values on object root

#### Actual behavior
Throw `TypeError: path should not be empty`

#### How to reproduce
See [runkit](https://runkit.com/embed/9bcqo9ffvk1z)

### Only for feature requests :sparkles:
Don't know if it's possible or a good practice, but it would be nice to be able to assign values on object root

#### Example
```js
const { assign } = require('immutadot')

const current = {}
const next = assign(current, '', { entities: {}, result: [] })
// { entities: {}, result: [] }
```

**Comment by frinyvonnick** [comment]
To apply operation on root object like yours you can write it like:

```js
const { assign } = require('immutadot')

const current = {}
const next = assign(current, '.', { entities: {}, result: [] })
// { entities: {}, result: [] }
```

**Comment by thcolin** [comment]
Thanks a lot, I should tried this !

**Comment by frinyvonnick** [comment]
My bad it will create an empty property with `{ entities: {}, result: [] }` in it

**Comment by frinyvonnick** [comment]
We won't implement operations on root object because javascript already provides tools for that. In your example `Object.assign({}, { entities: {}, result: [] })` is already immutable.

**Comment by thcolin** [comment]
No problems, thanks for your time !
