### ISSUE TITLE
Add other lodash Array functions

### ISSUE THREAD

**Issue by nlepage** [Zenika/immutadot#49]
### Description
- [ ] `differenceBy`
- [ ] `differenceWith`
- [ ] `dropRight`
- [ ] `dropRightWhile`
- [ ] `dropWhile`
- [ ] `fill`
- [ ] `intersection`
- [ ] `intersectionBy`
- [ ] `intersectionWith`
- [ ] `pullAll`
- [ ] `pullAllBy`
- [ ] `pullAllWith`
- [ ] `pullAt`
- [ ] `reverse`
- [ ] `slice`
- [x] `take`
- [x] `takeRight`
- [x] `takeRightWhile`
- [x] `takeWhile`
- [ ] `union`
- [ ] `unionBy`
- [ ] `without -> pull`
- [x] `xor`
- [ ] `xorBy`
- [ ] `xorWith`

**Comment by charlyx** [comment]
* [ ] omit?

**Comment by nlepage** [comment]
@charlyx `omit` is an object function, we have to create an issue to list the object functions
