### ISSUE TITLE
Wrong value in test description of remove feature

### ISSUE THREAD

**Issue by frinyvonnick** [Zenika/immutadot#57]
### Prerequisites
 - [x] I have read the [Contributing guidelines](https://github.com/Zenika/immutadot/blob/master/.github/CONTRIBUTING.md)
 - [x] I have read the [Code of conduct](https://github.com/Zenika/immutadot/blob/master/.github/CODE_OF_CONDUCT.md) and I agree with it

### Description
Wrong test description for `remove` feature

**Comment by nlepage** [comment]
To be fixed on branch 0.2, then merged in master.

**Comment by nlepage** [comment]
fixed in 0601885 and 3264962
