### ISSUE TITLE
typo in string namespace for capitalize function

### ISSUE THREAD

**Issue by frinyvonnick** [Zenika/immutadot#91]
### Prerequisites
 - [x] I have read the [Contributing guidelines](https://github.com/Zenika/immutadot/blob/master/.github/CONTRIBUTING.md)
 - [x] I have read the [Code of conduct](https://github.com/Zenika/immutadot/blob/master/.github/CODE_OF_CONDUCT.md) and I agree with it

### Description
There is a typo in index.js file in string namespace. There is a z instead of a t in method name.

```js
import { capizalize } from './capizalize'
import { replace } from './replace'
import { toLower } from './toLower'
import { toUpper } from './toUpper'

/**
 * String functions.
 * @namespace string
 * @since 0.3.0
 */
export {
  capizalize,
  replace,
  toLower,
  toUpper,
}
```
### Only for bugs :bug:
**Version :** 3.0.0

**Comment by nlepage** [comment]
closed by #92
